"""Write a validated WizardState to config.toml using tomlkit.

Produces a config the runtime's AppConfig.load accepts, and pre-provisions a
disabled [mcp] section so the Stage 4 MCP server can be enabled later without
editing the writer.
"""

from __future__ import annotations

from pathlib import Path

import tomlkit

from octoops.core.config import AppConfig
from octoops.core.envfile import format_env
from octoops.core.secure_io import write_private_text
from octoops.wizard.state import WizardState

_SECRET_MASK = "•" * 10


def _mask_bot_token(token: str) -> str:
    """Hide the secret half of a bot token for on-screen previews. The part before
    ':' is the bot's public numeric id (kept, so the operator can confirm the right
    bot); everything after it is the secret and is replaced."""
    prefix, sep, _ = token.partition(":")
    return f"{prefix}{sep}{_SECRET_MASK}" if sep else _SECRET_MASK


def build_document(state: WizardState) -> tomlkit.TOMLDocument:
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by the OctoOps setup wizard."))
    doc.add(tomlkit.nl())

    telegram = tomlkit.table()
    telegram["bot_token"] = state.bot_token
    telegram["admin_chat_id"] = state.admin_chat_id
    doc["telegram"] = telegram

    transport = tomlkit.table()
    transport["whatsapp_enabled"] = bool(state.use_whatsapp)
    transport["whatsapp_bridge_path"] = state.whatsapp_bridge_path
    transport["whatsapp_bridge_port"] = int(state.whatsapp_bridge_port)
    transport["octoops_callback_port"] = int(state.octoops_callback_port)
    # Startup-status recipients (cleared when WhatsApp itself is off).
    transport["whatsapp_admin_chat_ids"] = (
        list(state.whatsapp_admin_chat_ids) if state.use_whatsapp else []
    )
    # Optional brain-only inbound (forced off when WhatsApp itself is off).
    transport["whatsapp_inbound_enabled"] = bool(
        state.use_whatsapp and state.whatsapp_inbound_enabled
    )
    transport["whatsapp_allow"] = list(state.whatsapp_allow)
    transport["whatsapp_command"] = state.whatsapp_command
    transport["whatsapp_role"] = state.whatsapp_role
    doc["transport"] = transport

    core = tomlkit.table()
    core["timezone"] = state.timezone
    core["allowed_user_ids"] = list(state.allowed_user_ids)
    core["operator_user_ids"] = list(state.operator_user_ids)
    core["admin_user_ids"] = list(state.admin_user_ids)
    core["default_role"] = state.default_role
    core["log_file"] = state.log_file
    core["log_max_bytes"] = int(state.log_max_bytes)
    doc["core"] = core

    modules = tomlkit.table()
    modules["enabled"] = list(state.enabled_modules)
    for name, cfg in state.module_config.items():
        if not cfg:
            continue
        sub = tomlkit.table()
        for key, value in cfg.items():
            sub[key] = value
        modules[name] = sub
    doc["modules"] = modules

    # Optional MCP server (Stage 4), off by default. A second control plane:
    # enable deliberately and prefer a token. Command execution stays off unless
    # both allow_command_execution is true and a command opts in (ai_invokable).
    # On a re-run we carry the existing [mcp] block verbatim so setup never
    # silently disables a server the operator turned on by hand.
    if state.mcp_section is not None:
        mcp = tomlkit.table()
        for key, value in state.mcp_section.items():
            mcp[key] = value
    else:
        mcp = tomlkit.table()
        mcp.add(tomlkit.comment("Expose OctoOps as an MCP server (off by default)."))
        mcp["enabled"] = False
        mcp["host"] = "127.0.0.1"
        mcp["port"] = 3002
        mcp["service_role"] = "viewer"
        mcp["allow_command_execution"] = False
        mcp.add(tomlkit.comment('token = "set-a-bearer-token-to-require-auth"'))
    doc["mcp"] = mcp

    return doc


def state_from_config(config: AppConfig) -> WizardState:
    """Hydrate a WizardState from a loaded config — the inverse of build_document.

    Lets ``octoops --setup`` re-run as an *edit* of the existing config instead of
    starting from blank defaults (which silently dropped every prior setting).
    ``register_task`` is wizard-only and not stored in config, so it stays False.
    """
    mcp_section: dict[str, object] = {
        "enabled": config.mcp.enabled,
        "host": config.mcp.host,
        "port": config.mcp.port,
        "service_role": config.mcp.service_role.name.lower(),
        "allow_command_execution": config.mcp.allow_command_execution,
    }
    if config.mcp.token:
        mcp_section["token"] = config.mcp.token

    return WizardState(
        bot_token=config.telegram.bot_token,
        admin_chat_id=config.telegram.admin_chat_id,
        use_whatsapp=config.transport.whatsapp_enabled,
        whatsapp_bridge_path=config.transport.whatsapp_bridge_path,
        whatsapp_bridge_port=config.transport.whatsapp_bridge_port,
        octoops_callback_port=config.transport.octoops_callback_port,
        whatsapp_admin_chat_ids=list(config.transport.whatsapp_admin_chat_ids),
        whatsapp_inbound_enabled=config.transport.whatsapp_inbound_enabled,
        whatsapp_allow=list(config.transport.whatsapp_allow),
        whatsapp_command=config.transport.whatsapp_command,
        whatsapp_role=config.transport.whatsapp_role.name.lower(),
        timezone=config.core.timezone,
        allowed_user_ids=list(config.core.allowed_user_ids),
        operator_user_ids=list(config.core.operator_user_ids),
        admin_user_ids=list(config.core.admin_user_ids),
        default_role=config.core.default_role.name.lower(),
        log_file=config.core.log_file,
        log_max_bytes=config.core.log_max_bytes,
        enabled_modules=list(config.enabled_modules),
        module_config={
            name: dict(section) for name, section in config.module_sections.items()
        },
        mcp_section=mcp_section,
    )


def render_config(state: WizardState, *, redact_secrets: bool = False) -> str:
    """Render the config as TOML. With ``redact_secrets`` (for on-screen previews)
    the bot token and any MCP bearer token are masked; the written file is never
    redacted."""
    doc = build_document(state)
    if redact_secrets:
        if state.bot_token:
            doc["telegram"]["bot_token"] = _mask_bot_token(state.bot_token)
        mcp = doc.get("mcp")
        if mcp is not None and mcp.get("token"):
            mcp["token"] = _SECRET_MASK
    return tomlkit.dumps(doc)


def write_config(state: WizardState, path: str | Path) -> Path:
    # 0600: config.toml holds the bot token in cleartext — not world-readable.
    return write_private_text(path, render_config(state))


def render_env(state: WizardState) -> str:
    """Render the module secrets as .env text (ENV_NAME="value")."""
    return format_env(state.secrets)


def write_env(state: WizardState, path: str | Path) -> Path | None:
    """Write the secrets sidecar (0600). Returns None when there are no secrets."""
    if not state.secrets:
        return None
    return write_private_text(path, render_env(state))
